Repository kakao-tech-campus-2nd-step3/Team22_BE, pull requests merged in 2024-11, with the labels that each got.

#62 feat : DisplayId 를 사용해 유저 검색 기능 구현
  src/main/java/io/github/eappezo/soundary/core/user/UserRepository.java
  src/main/java/io/github/eappezo/soundary/services/user/api/controller/UserAPI.java
  src/main/java/io/github/eappezo/soundary/services/user/api/controller/UserController.java
  src/main/java/io/github/eappezo/soundary/services/user/application/service/UserService.java
  src/main/java/io/github/eappezo/soundary/services/user/infrastructure/persistence/repository/JpaUserRepository.java
  src/main/java/io/github/eappezo/soundary/services/user/infrastructure/persistence/repository/UserRepositoryImpl.java
Labels: ⭐Feature

#70 [Docs] 독스 구체화
  src/main/java/io/github/eappezo/soundary/services/user/api/dto/UserUpdateRequest.java
Labels: documentation

#80 [Test] MusicShareServiceTest 작성
  src/test/java/io/github/eappezo/soundary/services/music/application/share/service/MusicShareServiceTest.java
Labels: 📗Test
